{ config, modulesPath, pkgs, lib, nixos-lima, localConfig,... }:
{
    imports = [
      (modulesPath + "/profiles/qemu-guest.nix")
      # The `lima` module sets up systemd services to support LimaVM
      nixos-lima.nixosModules.lima
    ];

    networking.hostName = "nixbitcoin-regtest";
    time.timeZone = "${localConfig.timeZone}";

    # TODO: Consider setting some/all of the mandatory settings in `nixos-lima.nixosModules.lima`

    # Enable lima-init, lima-guestagent, other config needed for Lima support (via `nixos-lima.nixosModules.lima`)
    services.lima.enable = true;

    users.users.${localConfig.userAccountName} = {
      isNormalUser = true;
      extraGroups = [
        "wheel"      # Allows the user to use 'sudo'
      ];
      home = "/home/${localConfig.userAccountName}.linux";  # Lima appends .linux to homedir by default
    };

    # Using Flakes is highly-recommended, maybe even required.
    nix.settings.experimental-features = [ "nix-command" "flakes" ];
    nix.settings.trusted-users = [ "@wheel" ];

    # ssh
    services.openssh.enable = true;

    security = {
        sudo.wheelNeedsPassword = false;
    };

    # system mounts
    # These settings match the image file generated by the NixOS Lima VM image generator
    boot.loader.grub = {
        device = "nodev";
        efiSupport = true;
        efiInstallAsRemovable = true;
    };
    fileSystems."/boot" = {
        device = lib.mkForce "/dev/vda1";  # /dev/disk/by-label/ESP
        fsType = "vfat";
    };
    fileSystems."/" = {
        device = "/dev/disk/by-label/nixos";
        autoResize = true;
        fsType = "ext4";
        options = [ "noatime" "nodiratime" "discard" ];
    };

    # misc
    boot.kernelPackages = pkgs.linuxPackages_latest;

    # pkgs
    environment.systemPackages = with pkgs; [
        vim
    ];

    # The usual warnings about changing `stateVersion` apply. Make sure to find and read them
    # before changing this value.
    system.stateVersion = "25.05";
}
